<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pillar</string>
		<string>pier</string>
	</array>
	<key>name</key>
	<string>Pillar</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^!{1,6}.+$</string>
			<key>name</key>
			<string>markup.heading.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"".+""</string>
			<key>name</key>
			<string>markup.bold.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>''.+''</string>
			<key>name</key>
			<string>markup.italic.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>--.+--</string>
			<key>name</key>
			<string>markup.other.stri­ket­hro­ugh.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>__.+__</string>
			<key>name</key>
			<string>markup.underline.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>==.+==</string>
			<key>name</key>
			<string>markup.raw.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@@.+@@</string>
			<key>name</key>
			<string>markup.other.subs­cript.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\^\^.+\^\^</string>
			<key>name</key>
			<string>markup.other.su­pers­cri­pt.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*.+\*</string>
			<key>name</key>
			<string>markup.underline.link.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+.+\+</string>
			<key>name</key>
			<string>markup.underline.link.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^- .+$</string>
			<key>name</key>
			<string>markup.list.unordered.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^# .+$</string>
			<key>name</key>
			<string>markup.list.ordered.pillar</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[\[\[</string>
			<key>end</key>
			<string>]]]([^\S\n]*[\n])?</string>
			<key>name</key>
			<string>markup.raw.block.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%.+$</string>
			<key>name</key>
			<string>comment.percentage.pillar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\w+</string>
			<key>name</key>
			<string>entity.name.tag</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pillar</string>
	<key>uuid</key>
	<string>2EEF5662-10BC-42C7-A64E-AAA494B9B3CE</string>
</dict>
</plist>
